### ISSUE TITLE
Atmosphere improperly set with rhostar fix in IllinoisGRMHD (typo)

### ISSUE THREAD

**Issue by Sbozzolo** [zachetienne/nrpytutorial#19]
I think that there's a minor copy&paste error at line 853 of the file `IllinoisGRMHD/doc/Tutorial-IllinoisGRMHD__the_conservative_to_primitive_algorithm.ipynb`.  

Extract of the current file (lines 852-853):
```c
"          CCTK_REAL K_ppoly_tab     = eos.K_ppoly_tab[polytropic_index];\n",
"          CCTK_REAL Gamma_ppoly_tab = eos.K_ppoly_tab[polytropic_index];\n",
```

Shouldn't it be
```c
"          CCTK_REAL K_ppoly_tab     = eos.K_ppoly_tab[polytropic_index];\n",
"          CCTK_REAL Gamma_ppoly_tab = eos.Gamma_ppoly_tab[polytropic_index];\n",
``` 
?

**Comment by leowerneck** [comment]
Thank you for letting us know of the bug! Indeed, it should be exactly as you suggested. I have updated the conservative-to-primitive Jupyter notebook with the corrected version.
