### ISSUE TITLE
ranges over which to loop

### ISSUE THREAD

**Issue by rhaas80** [zachetienne/nrpytutorial#20]
In https://github.com/zachetienne/nrpytutorial/blob/master/Tutorial-Solving_the_Scalar_Wave_Equation_with_NumPy.ipynb the range over which to loop is given as `for i in range(NGHOSTS, Nx+NGHOSTS)` etc. While correct (`Nx` is the number of interior points) it may be more intuitive to write this as `for i in range(NGHOSTS, NGHOSTS+Nx)` to provide more of an indication that the range is "from `NGHOSTS` to `Nx` points past `NGHOSTS`" rather than "to `NGHOSTS` points more than `Nx`").

**Comment by zachetienne** [comment]
Thanks for the suggestion Roland! 

As I recall I was on the fence about Nx+NGHOSTS or NGHOSTS+Nx a long time ago, but settled on the former for the following reason:

We declare as a parameter e.g., Nxx_plus_2NGHOSTS0 as a shortcut to Nxx0+2*NGHOSTS (which would be the total number of points in the x direction on a Cartesian grid). If we were instead to write it 2*NGHOSTS+Nxx0 (mathematically equivalent), the name would be 2NGHOSTS_plus_Nxx0, which throws a compilation error (integers aren't allowed at the start of variable names in C).
