### ISSUE TITLE
nrpyplus Tutorial notebook start-to-Finish Example: Scalar Field Collapse tries to download ffmpeg from old link

### ISSUE THREAD

**Issue by kotenok2000** [zachetienne/nrpytutorial#45]
https://notebooks.gesis.org/binder/jupyter/user/zachetienne-nrpytutorial-tqha3xtc/notebooks/Tutorial-Start_to_Finish-BSSNCurvilinear-ScalarField_Collapse.ipynb
It tries to download ffmpeg from http://astro.phys.wvu.edu/zetienne/ffmpeg-static-amd64-johnvansickle.tar.xz

**Comment by zachetienne** [comment]
@kotenok2000 : Thanks for letting us know! Git commit https://github.com/zachetienne/nrpytutorial/commit/35515c4968e448e7f972b9fafee28a7943153233 has fixed this problem. In addition I am fixing all links to my former website astro.phys.wvu.edu/zetienne/* (commits to come).
