### ISSUE TITLE
One error happens when using cmdline_helper.

### ISSUE THREAD

**Issue by wc1018** [zachetienne/nrpytutorial#86]
_**Code:**_

```
import cmdline_helper as cmd
cmd.new_C_compile(Ccodesrootdir, os.path.join("output", "BrillLindquist_Playground"),
                  uses_free_parameters_h=True, compiler_opt_option="fast") # fastdebug or debug also supported

# Change to output directory
os.chdir(os.path.join(Ccodesrootdir, "output"))
# Clean up existing output files
cmd.delete_existing_files("out*.txt")
cmd.delete_existing_files("out*.png")
# Run executable with CFL_FACTOR = 1.0, which is allowed since
#   simulation is axisymmetric and all phi derivs are set to zero.
# cmd.Execute("BrillLindquist_Playground", "72 12 2 "+str(CFL_FACTOR))
# cmd.Execute("BrillLindquist_Playground", "800 16 2 "+str(CFL_FACTOR))
cmd.Execute("BrillLindquist_Playground", str(Nr) + " " + str(Nth) + " " + str(Nph) + " " + str(CFL_FACTOR))
os.chdir(os.path.join("..", ".."))
```

_**Then jupyter shows an error:**_

```
File D:\Anaconda3_2309\Lib\subprocess.py:1538, in Popen._execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_gid, unused_gids, unused_uid, unused_umask, unused_start_new_session, unused_process_group)
   1536 # Start the process
   1537 try:
-> 1538     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
   1539                              # no special security
   1540                              None, None,
   1541                              int(not close_fds),
   1542                              creationflags,
   1543                              env,
   1544                              cwd,
   1545                              startupinfo)
   1546 finally:
   1547     # Child is launched. Close the parent's copy of those pipe
   1548     # handles that only the child should have open.  You need
   (...)
   1551     # pipe will not close when the child process exits and the
   1552     # ReadFile will hang.
   1553     self._close_pipe_fds(p2cread, p2cwrite,
   1554                          c2pread, c2pwrite,
   1555                          errread, errwrite)

OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
```

**Comment by zachetienne** [comment]
While this old version of NRPy (1.0) has better support for Windows, there are no guarantees that any notebook will work with Windows. You may want to try running the notebook in mybinder:
https://mybinder.org/v2/gh/zachetienne/nrpytutorial/master?filepath=NRPyPlus_Tutorial.ipynb
If the problems do not appear there, then the problem is compatibility with your Windows environment.
The latest version of NRPy (2.0) can be found here:
https://github.com/nrpy/nrpy

**Comment by zachetienne** [comment]
Also you may find this helpful:
https://docs.google.com/presentation/d/1mtdfHpF7eM-mevgBQliBdcfdJaBbg4Q1w7K5z2l2GuI/edit?usp=sharing

**Comment by wc1018** [comment]
Is there any detailed tutorial for NRPy(2.0)? I want to learn how to operate with the example project produced using nrpy2.0, like how to produce the waveforms of two colliding black holes. According to the given short tutorial of nrpy2.0, it seems that we can only see the results in the out***.txt files which doesn't contain something like the waveform.

**Comment by zachetienne** [comment]
Oh, that's because the waveform analysis in NRPy 2.0 is associated not with the `two_blackholes_collide` example but the `blackhole_spectroscopy` example. After running the latter, you'll see data files `Rpsi4_l2*` that contain the waveform content (in the form of a spin-weight -2 decomposed $\psi_4$ Weyl scalar) at different radii.

**Comment by wc1018** [comment]
I see. Thank you! Concerning the error of cmdline_helper, I find that's mainly caused by my windows environment compatibility. When I run NRPy(1.0) in the Linux system, the error disappears automatically.
